name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CHECKFLOW_PEM: ${{ secrets.CHECKFLOW_PEM }}

        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | head -c 5
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | head -c 5
          echo "${{ secrets.CHECKFLOW_PEM }}" | head -c 5


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Lint with Flake8
        run: |
          flake8

      - name: Format with isort
        run: |
          isort . --check-only

      - name: Run Tests
        run: |
          coverage run app/manage.py test app

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHECKFLOW_PEM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-35-180-227-151.eu-west-3.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-west-3

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-35-180-227-151.eu-west-3.compute.amazonaws.com << 'ENDSSH'
          cd checkflow-api
          ENDSSH