name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Lint with Flake8
        run: |
          flake8

      - name: Format with isort
        run: |
          isort . --check-only

      - name: Run Tests
        run: |
          coverage run app/manage.py test app

      - name: Set up SSH connection
        env:
          EC2_CERTIFICATE: ${{ secrets.EC2_CERTIFICATE }}  # Ensure this secret name is correct
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_CERTIFICATE }}" > ~/.ssh/ec2_key.pem
          echo ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H 15.236.193.68 >> ~/.ssh/known_hosts

      - name: SSH Command Execution
        run: |
          ssh -i ~/.ssh/ec2_key.pem ubuntu@ec2-15-236-193-68.eu-west-3.compute.amazonaws.com  'echo "Connected to EC2"'
