name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Lint with Flake8
        run: |
          flake8

      - name: Format with isort
        run: |
          isort . --check-only

      - name: Run Tests
        run: |
          coverage run app/manage.py test app

      - name: Deploy to EC2
        env:
          CHECKFLOW_PEM: ${{ secrets.CHECKFLOW_PEM }}
        run: |
          mkdir -p ~/.ssh
          echo "$CHECKFLOW_PEM" > checkflow.pem
          chmod 600 checkflow.pem
          ssh-keyscan -H ec2-35-180-227-151.eu-west-3.compute.amazonaws.com >> ~/.ssh/known_hosts
          ssh -i "checkflow.pem" -o StrictHostKeyChecking=no ubuntu@ec2-35-180-227-151.eu-west-3.compute.amazonaws.com << 'ENDSSH'
          cd checkflow-api
          git pull origin develop
          ENDSSH